### ISSUE TITLE
Show at least some of what's in a node by default

### ISSUE THREAD

**Issue by Keno** [bicycle1885/EzXML.jl#106]
This output isn't super helpful in interactive use:
```
invlist = findall("//...", xdoc)
1-element Array{EzXML.Node,1}:
 EzXML.Node(<ELEMENT_NODE@0x00007ffbac7a7d20>)
```
It would be nice to print at least some of the node properties (e.g. the tag name).

**Comment by bicycle1885** [comment]
Thanks. Now it shows the name of element and attribute nodes like `EzXML.Node(<ELEMENT_NODE[name]@0x00007ffbac7a7d20>)`.
