### ISSUE TITLE
findfirst(node,xpath) returns BoundsError if the node is not found

### ISSUE THREAD

**Issue by hshindo** [bicycle1885/EzXML.jl#11]
In such case, maybe it would be better to return nothing or empty node.
Or, to be consistent with Base, it may return index rather than node.

**Comment by bicycle1885** [comment]
Sounds a reasonable suggestion. However, we'll need to find a consistent way in EzXML.jl. There are many functions in EzXML.jl that may fail to find a query node (`nextnode`, `parentnode`, etc.). These functions should behave consistently.

**Comment by hshindo** [comment]
Right.
Is it reasonable that `find` returns empty array but `findfirst` throws an error if the node is not found?
If so, there's no problem.

**Comment by bicycle1885** [comment]
As outlined in #51, I'm going to make `findfirst`/`findlast` return `nothing` when there is no matching node, which is already on the master branch (#57). This change will be consistent with these methods of Base on Julia 0.7/1.0. For example, `findfirst(x -> x < 0, [1,2,3])` will return `nothing` in the next release of Julia.
