### ISSUE TITLE
Failing to download binary dependencies on MacOS

### ISSUE THREAD

**Issue by juliohm** [bicycle1885/EzXML.jl#118]
I am depending on this package indirectly through XLSX.jl. The build is failing on MacOS, and it seems like a URL issue:

>ERROR: LoadError: Coud not download "https://github.com/bycycle1885/XLM2Builder/releases/download/v1.0.2/XLM2Builder.v2.9.9.x86_64-apple-darwin14.tar.gz"

**Comment by bicycle1885** [comment]
The URL looks strange. The correct one is "...github.com/bicycle1885/...", not "...github.com/bycycle1885/...". Also, I cannot reproduce the problem.

**Comment by juliohm** [comment]
Maybe I typed the url incorrectly in the issue. I couldn't copy paste
because the error was in another computer.

What can I do to help debug further ?

**Comment by bicycle1885** [comment]
Well, I need information about versions, platforms, and minimal examples. Can you install EzXML.jl directly by `add EzXML`? Also, can you install other packages that uses BinaryProvider.jl? (e.g. CodecZlib.jl).

**Comment by juliohm** [comment]
You are right, I've installed EzXML.jl directly, and it builds successfully now. It should be a version issue in the XLSX.jl dependency file. Thank you for the prompt reply.
