### ISSUE TITLE
Xpath by ignoring namespace (for local names)

### ISSUE THREAD

**Issue by aminya** [bicycle1885/EzXML.jl#124]
How can I do Xpath for local names by ignoring namespaces?
https://stackoverflow.com/questions/4440451/how-to-ignore-namespaces-with-xpath

The error arises when we want to do Xpath for a Node when it doesn't have a doc

**Comment by PallHaraldsson** [comment]
I don't know the answer (I've no relation to this project), but I like to point out it's a wrapper for:

http://xmlsoft.org/

so possibly documentation on it (how to do in e.g. C), is helpful, as it would translate to here.

Note also other projects pointed to from this project, e.g.:

https://github.com/JuliaIO/LightXML.jl

It seems to be a wrapper for the same library. I'm not sure if either or both is an incomplete wrapper, or if either is redundant. Both have at least been updated recently.

In general (at least at Julialang's github) issues aren't to ask questions, I'm not sure if discouraged here too. For Julia there's discourse.julialang.org (and slack, and reddit and other to ask questions). It may apply to this too, probably all questions on packages too are welcome at some of these places, but for this I'm not sure where best to point to.

**Comment by aminya** [comment]
I solved this by my own code:
https://github.com/aminya/AcuteML.jl/blob/d527a1a6558b583190cafd2bb7017d22e8a41abe/src/utilities.jl#L15
