### ISSUE TITLE
Keeping track of added elements

### ISSUE THREAD

**Issue by aminya** [bicycle1885/EzXML.jl#126]
Is there a way to keep track of added elements to access them fast later?
For example,
```julia
addelement!(node, name, value)
```
adds an element to the `node`. Is there a way to keep track of this added element to access it later (without the need to search again through the whole XML file).

**Comment by bicycle1885** [comment]
Hi, you can use the returned value of `addelement!` like below:
```
julia> parent = ElementNode("parent")
EzXML.Node(<ELEMENT_NODE[parent]@0x00007f7face01c70>)

julia> child = addelement!(parent, "child")
EzXML.Node(<ELEMENT_NODE[child]@0x00007f7facb00140>)

julia> println(parent)
<parent><child/></parent>

julia> println(child)
<child/>

```
