### ISSUE TITLE
warning message always prints

### ISSUE THREAD

**Issue by tbeason** [bicycle1885/EzXML.jl#135]
When parsing a particular XML file, I always get this warning
```
┌ Warning: ignored the empty prefix for 'http://www.w3.org/2005/Atom'; expected to be non-empty
└ @ EzXML ~/.julia/packages/EzXML/ZNwhK/src/xpath.jl:85
```

Here is a snippet of the top of the file, which I think is probably the only relevant portion.
```
<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<feed xml:base="http://data.treasury.gov/Feed.svc/" xmlns:d="http://schemas.microsoft.com/ado/2007/08/dataservices" xmlns:m="http://schemas.microsoft.com/ado/2007/08/dataservices/metadata" xmlns="http:/www.w3.org/2005/Atom">
```

I am able to parse the file, but the warning always prints. Is there a way to either turn it off or for me to change how I parse the file so that it does not show?

**Comment by tbeason** [comment]
For more reference, here is the package that I am using EzXML with. https://github.com/tbeason/DailyTreasuryYieldCurve.jl

**Comment by bicycle1885** [comment]
I think parsing itself does not warn you; some XPath operation does. Have you checked this example? https://github.com/bicycle1885/EzXML.jl/blob/830d3c2bd73ff96b5cb69e854a47117c2c93cf8a/test/runtests.jl#L1284-L1294
