### ISSUE TITLE
Performance implications of getproperty

### ISSUE THREAD

**Issue by GordStephen** [bicycle1885/EzXML.jl#139]
First - I really like this package, thanks for all your work on it!

I wanted to flag that (as far as I know) defining `getproperty` for `StreamReader` forces field lookups to always have to go through the property method, which incurs a fairly significant performance penalty since doing pretty much anything with a stream involves accessing `reader.ptr` . While the properties are convenient, the most common applications for `StreamReader` are presumably performance-sensitive, where the extra verbosity of `nodename(reader)` over `reader.name` is well worth the performance gain.

While I haven't done extensive benchmarking, I can report anecdotally that in my own streaming parsing application I'm seeing 3x performance improvements just by commenting out the `getproperty` method.

https://github.com/bicycle1885/EzXML.jl/blob/2b9ea9b01d8b601a4d988bdc19500739ab9be3b6/src/streamreader.jl#L21-L28

I know this is a breaking change and that the package is post-1.0, but (unless I'm missing some way of turning this off?) high performance streaming parsing doesn't really seem feasible as-is.

**Comment by bicycle1885** [comment]
Thank you for reporting! I'm a little bit surprised because I thought Julia was smart enough to inline the function and the overhead would be zero. This performance problem will be fixed by #142 without breaking changes.

**Comment by GordStephen** [comment]
Thanks! Clever to just call `getfield` directly, not sure why I didn’t think of that.
