### ISSUE TITLE
InexactError() at line 91 parsing graphml file

### ISSUE THREAD

**Issue by nickeubank** [bicycle1885/EzXML.jl#17]
Trying to load a graphml file using the GraphIO library, and am hitting a problem which it appears may be coming from EzXML, and I was hoping someone might be able to at least point me in the direction of a solution. 

The error:

    julia> g = loadgraph("/users/nick/desktop/anonmonths.graphml", "G", GraphMLFormat())
    ERROR: InexactError()
    Stacktrace:
     [1] macro expansion at /Users/Nick/.julia/v0.6/EzXML/src/error.jl:50 [inlined]
     [2] parsexml(::String) at /Users/Nick/.julia/v0.6/EzXML/src/document.jl:91
     [3] loadgraphml(::GZip.GZipStream, ::String) at /Users/Nick/.julia/v0.6/GraphIO/src/graphml.jl:30
     [4] gzopen(::LightGraphs.##109#110{String,GraphIO.GraphMLFormat}, ::String, ::String) at /Users/Nick/.julia/v0.6/GZip/src/GZip.jl:268
     [5] loadgraph(::String, ::String, ::GraphIO.GraphMLFormat) at /Users/Nick/.julia/v0.6/LightGraphs/src/persistence/common.jl:14

The graph I'm trying to load is pretty big -- about 10 million nodes, 16 million edges -- and has two node attributes (if that matters). Here's the head of the file:

  
    <?xml version="1.0" encoding="UTF-8"?>
    <graphml xmlns="http://graphml.graphdrawing.org/xmlns"
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:schemaLocation="http://graphml.graphdrawing.org/xmlns
           http://graphml.graphdrawing.org/xmlns/1.0/graphml.xsd">
    
    <key id="v_id" for="node" attr.name="id" attr.type="string"/>
    <key id="v_pt" for="node" attr.name="pt" attr.type="boolean"/>
    <graph id="G" edgedefault="undirected">
      <node id="n0">
        <data key="v_id">n0</data>
        <data key="v_pt">false</data>
      </node>
      <node id="n1">
        <data key="v_id">n1</data>
        <data key="v_pt">true</data>
      </node>
      <node id="n2">
        <data key="v_id">n2</data>
        <data key="v_pt">true</data>
      </node>
      <node id="n3">
        <data key="v_id">n3</data>
        <data key="v_pt">true</data>
      </node>
      <node id="n4">
        <data key="v_id">n4</data>
        <data key="v_pt">true</data>
      </node>
      <node id="n5">

...

Full file is 2.16 gigs and (frustration of frustrations) I can't share it, and can't seem to come up with a MWE with a similar looking random graph. Any suggestions welcome!

**Comment by bicycle1885** [comment]
Do you use EzXML v0.4.4? The most suspicious part is here: https://github.com/bicycle1885/EzXML.jl/blob/v0.4.4/src/document.jl#L95, which converts the input data size to a 32-bit signed integer. Your file size seems to be larger than 2147483647 (= `typemax(Cint)`) and hence it cannot be converted to the type.

If so, a quick solution would be using `readxml(io::IO)` method to load a large XML file from a stream instead of reading all data at once. However, it still consumes huge amount of memory because it needs to build a large XML tree in memory. I think the best approach would be using `StreamReader` APIs, which does not build an XML tree and is suitable for large XML files.

**Comment by bicycle1885** [comment]
I think replacing `xdoc = parsexml(readstring(io))` with `xdoc = readxml(io)` in https://github.com/JuliaGraphs/GraphIO.jl/blob/master/src/graphml.jl will solve the problem.

**Comment by nickeubank** [comment]
@bicycle1885 you're the best, thanks!

**Comment by bicycle1885** [comment]
I close this issue since it has been solved in the upstream.
