### ISSUE TITLE
Tests should use running julia version for examples rather than whichever is on path

### ISSUE THREAD

**Issue by tkelman** [bicycle1885/EzXML.jl#22]
The `#!/usr/bin/env julia` line in the examples is fine, but the "Examples" testset shouldn't be relying on it to run them. It might be an entirely different version of Julia, or none at all, on the path.

**Comment by tkelman** [comment]
ping @bicycle1885

**Comment by bicycle1885** [comment]
Ah, thank you. #23 will fix it.
