### ISSUE TITLE
Information is lost when node name contains `:` ?

### ISSUE THREAD

**Issue by YongHee-Kim** [bicycle1885/EzXML.jl#52]
``` Julia
using EzXML 

doc = root(parsexml("""
<sheets>
    <sheet name="FAM" sheetId="1" d3p1:id="rId1" xmlns:d3p1="xxx" />
  </sheets>
"""))

mynode = attributes.(elements(doc)[1])

nodename.(mynode)
```
It gives me `["name", "sheedId", "id"]` instead of `["name", "sheetId", "d3p1:id", "xmlns:d3p1"]`
and there are only 3 attributes, the last attribute `xmlns:d3p1` is not accessible.

**Comment by bicycle1885** [comment]
Attribute names before `:` indicate a namespace: <https://www.w3schools.com/xml/xml_namespaces.asp>. `xmlns` is a default namespace. Namespaces are not a part of a node name.
