### ISSUE TITLE
Access XML declaration information

### ISSUE THREAD

**Issue by ararslan** [bicycle1885/EzXML.jl#72]
There doesn't appear to be a way to access the version and encoding declared in an XML document. For reference, LightXML has `version` and `encoding` functions that just do `getfield` on a Julia type with the same layout as the corresponding C struct. Have I overlooked something, or is this not currently possible with EzXML?

**Comment by bicycle1885** [comment]
Thank you for noticing it. `version` and `encoding ` will be added by #73.
